"""empty message

Revision ID: a404d24968dd
Revises: ced7c6598f1f
Create Date: 2021-07-03 22:07:27.684872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a404d24968dd'
down_revision = 'ced7c6598f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('header', sa.String(length=512), nullable=True),
    sa.Column('commitment', sa.String(), nullable=True),
    sa.Column('type_of_work', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_first_name'), 'profiles', ['first_name'], unique=False)
    op.create_index(op.f('ix_profiles_header'), 'profiles', ['header'], unique=False)
    op.create_index(op.f('ix_profiles_last_name'), 'profiles', ['last_name'], unique=False)
    op.create_index(op.f('ix_profiles_title'), 'profiles', ['title'], unique=False)
    op.create_table('profile_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=256), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_education_school'), 'profile_education', ['school'], unique=False)
    op.create_table('profile_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('commitment', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_jobs_company'), 'profile_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_profile_jobs_title'), 'profile_jobs', ['title'], unique=False)
    op.create_table('profile_langs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_langs_lang'), 'profile_langs', ['lang'], unique=False)
    op.create_table('profile_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_messages_timestamp'), 'profile_messages', ['timestamp'], unique=False)
    op.create_table('profile_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_projects_description'), 'profile_projects', ['description'], unique=False)
    op.create_index(op.f('ix_profile_projects_name'), 'profile_projects', ['name'], unique=False)
    op.create_table('profile_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('exp', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_skills_description'), 'profile_skills', ['description'], unique=False)
    op.create_index(op.f('ix_profile_skills_name'), 'profile_skills', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_skills_name'), table_name='profile_skills')
    op.drop_index(op.f('ix_profile_skills_description'), table_name='profile_skills')
    op.drop_table('profile_skills')
    op.drop_index(op.f('ix_profile_projects_name'), table_name='profile_projects')
    op.drop_index(op.f('ix_profile_projects_description'), table_name='profile_projects')
    op.drop_table('profile_projects')
    op.drop_index(op.f('ix_profile_messages_timestamp'), table_name='profile_messages')
    op.drop_table('profile_messages')
    op.drop_index(op.f('ix_profile_langs_lang'), table_name='profile_langs')
    op.drop_table('profile_langs')
    op.drop_index(op.f('ix_profile_jobs_title'), table_name='profile_jobs')
    op.drop_index(op.f('ix_profile_jobs_company'), table_name='profile_jobs')
    op.drop_table('profile_jobs')
    op.drop_index(op.f('ix_profile_education_school'), table_name='profile_education')
    op.drop_table('profile_education')
    op.drop_index(op.f('ix_profiles_title'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_header'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_first_name'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
