"""empty message

Revision ID: ced7c6598f1f
Revises: 
Create Date: 2021-07-03 19:00:48.197175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced7c6598f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_mobile_phone', table_name='services')
    op.create_index(op.f('ix_services_mobile_phone'), 'services', ['mobile_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_mobile_phone'), table_name='services')
    op.create_index('ix_services_mobile_phone', 'services', ['mobile_phone'], unique=True)
    # ### end Alembic commands ###
